### PR TITLE
modifications to build for 9.3.0

### PR DESCRIPTION
**Pull request by aadrian**
modifications to build for 9.3.0

### CODE REVIEW

**Comment by sajiljosephs** [comment]
@chatman @epugh @noblepaul @shalinmangar @vthacker  Can you check and merge this ?

**Comment by chatman** [comment]
Thanks a lot @aadrian . Will test and merge this tonight!

**Comment by sajiljosephs** [comment]
@chatman Can we have an update here on the latest version ?

**Comment by sajiljosephs** [comment]
@chatman It would be great if you can test this and merge at the earliest

**Comment by chatman** [comment]
Sure Sajil, I'll test and merge by this weekend. Thanks for your patience.

**Comment by sajiljosephs** [comment]
@chatman Thanks.

**Comment by chatman** [comment]
I've merged this, working on release automation and it should be done by
tonight. Thanks!

**Comment by sajiljosephs** [comment]
I still dont see 9.3.0

**Comment by chatman** [comment]
https://github.com/SearchScale/dataimporthandler/releases

**Comment by chatman** [comment]
Binary files can now come from released artifacts. The repository.json file
refers to that location. Hence, hosting the artifacts inside the repository
is no longer needed.

**Comment by sajiljosephs** [comment]
Can I have the repository URL ?
Add repository:

bin/solr package add-repo data-import-handler "https://raw.githubusercontent.com/searchscale/dataimporthandler/master/repo/"

**Comment by chatman** [comment]
Yes, that should work:

https://raw.githubusercontent.com/searchscale/dataimporthandler/master/repo/

There is a repository.json file there:
https://raw.githubusercontent.com/searchscale/dataimporthandler/master/repo/repository.json

**Comment by sajiljosephs** [comment]
{
        "version": "9.3.0",
        "date": "2023-09-08",
        "artifacts": [
          {
            "url": "https://github.com/SearchScale/dataimporthandler/releases/download/v9.3.0/data-import-handler-9.3.0.jar",
            "sig": "qDwa9rdEp6a1tWMgJaVnuni7eU20/M3oudpnD+ttPpV/ydfE+1/5cT5tSJAgRjNUABG8LxPOqcACFY6so32rkQ=="
          },
          {
            "url": "https://github.com/SearchScale/dataimporthandler/releases/download/v9.3.0/mariadb-java-client-2.6.0.jar",
            "sig": "SfYkFEkpqNfytOeGYNTSB0VD1sNLvTFQR9oCRv+e2y6GzawaZHBGo+9nKrZJ/4MUDVxQLfOiyaEJyQOI8Y+L7A=="
          }
        ],
        "manifest": {
          "version-constraint": "9.3.0",
          "plugins": [
            {
              "name": "request-handler",
              "setup-command": {
                "path": "/api/collections/${collection}/config",
                "payload": {
                  "add-requesthandler": {
                    "name": "${RH-HANDLER-PATH}",
                    "class": "data-import-handler:org.apache.solr.handler.dataimport.DataImportHandler",
                    "defaults": {
                      "config": "data-config.xml"
                    }
                  }
                },
                "method": "POST"
              },
              "uninstall-command": {
                "path": "/api/collections/${collection}/config",
                "payload": {
                  "delete-requesthandler": "${RH-HANDLER-PATH}"
                },
                "method": "POST"
              },
              "verify-command": {
                "path": "/api/collections/${collection}/config/requestHandler?componentName=${RH-HANDLER-PATH}&meta=true",
                "method": "GET",
                "condition": "$[config].[requestHandler].[HANDLER-PATH].[_packageinfo_].[version]",
                "expected": "${package-version}"
              }
            }
          ],
          "parameter-defaults": {
            "RH-HANDLER-PATH": "/dataimport"
          }
        }
      }
    ]
  }
]
 (through reference chain: java.util.ArrayList[0]->org.apache.solr.packagemanager.DefaultPackageRepository["packages"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:323)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:780)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:479)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:318)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4719)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3964)
	at org.apache.solr.packagemanager.RepositoryManager.addRepository(RepositoryManager.java:124)
	at org.apache.solr.cli.PackageTool.runImpl(PackageTool.java:106)
	at org.apache.solr.cli.ToolBase.runTool(ToolBase.java:52)
	at org.apache.solr.cli.SolrCLI.main(SolrCLI.java:156)
Caused by: org.apache.solr.client.solrj.impl.BaseHttpSolrClient$RemoteSolrException: Error from server at https://raw.githubusercontent.com/searchscale/dataimporthandler/master/repo/repository.json?wt=json&version=2.2: Expected mime type in [application/json] but got text/plain.

**Comment by chatman** [comment]
Thanks for reporting, I'll take a look tonight.

**Comment by chatman** [comment]
There's something wrong with Solr 9.3's JSON parsing that it refuses to read from github.com's repo :-( Looking into it.

**Comment by epugh** [comment]
I think I fixed it in 9.4 ;-(....

**Comment by epugh** [comment]
See https://github.com/apache/solr/commit/8ad05dec8ac2439856bd7841448a5dbdcc080f2f

**Comment by sajiljosephs** [comment]
@epugh When can we expect 9.4 release for solr ?

**Comment by chatman** [comment]
The 9.4 release is held up by Lucene 9.8 release. I would bet another two
weeks from now for the 9.4 release, though it can get delayed more as well.

**Pull request merged**
