### PR TITLE
Updating Solr Version to 9.6

### PR DESCRIPTION
**Pull request by naddanki87**

### CODE REVIEW

**Review by chrajesh — APPROVED** [review]
change looks good to me

**Comment by chatman** [comment]
Thanks @naddanki87 @chrajesh ! Sorry for the delay.

**Comment by chatman** [comment]
Done, released https://github.com/SearchScale/dataimporthandler/releases/tag/v9.6.1
@chrajesh I've invited you as a committer for this project and also listed the steps to do releases in the README.
Thank you for your help and support and all the best!

**Comment by epugh** [comment]
Nice to see releases!

**Pull request merged**
